import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";

const schema = z.object({
  data: z.date(),
  descricao: z.string(),
  valor: z.preprocess(
    (value) => String(value).replaceAll(",", "."),
    z.coerce
      .number({
        required_error: "Campo obrigatório",
        invalid_type_error: "Insira um valor numérico",
      })
      .min(0.01, "Insira um valor maior que zero")
  ),
  despesa: z.enum([
    "MORADIA",
    "CONDOMINIO",
    "ALUGUEL",
    "SUPERMERCADO",
    "AGUA",
    "LUZ",
    "GAS",
    "INTERNET",
    "IPTU",
    "PLANO_DE_SAUDE",
    "SEGURO_DE_VIDA",
    "INVESTIMENTO",
    "CARTAO_DE_CREDITO",
    "COMBUSTIVEL",
    "FARMACIA",
    "GASTOS_COM_ANIMAIS",
    "IMPREVISTOS",
    "ASSINATURA_VIDEO",
    "ASSINATURA_MUSICA",
    "PADARIA",
    "FEIRA",
    "LAZER",
    "SALAO",
    "TARIFAS_BANCARIAS",
    "PLANO_CELULAR",
    "IPVA",
    "CONSULTA_MEDICA",
    "CURSO",
    "DIVERSOS",
  ]),
  categoria: z.enum([
    "ALIMENTACAO",
    "TRANSPORTE",
    "SAUDE",
    "EDUCACAO",
    "LAZER",
    "HABITACAO",
    "CONTAS",
    "VESTUARIO",
    "OUTROS",
  ]),
  banco: z.enum([
    "BANCO_DO_BRASIL",
    "BANRISUL",
    "BITSO",
    "BITCOINTRADE",
    "BINANCE",
    "BRADESCO",
    "BS2",
    "BTG_PACTUAL",
    "CAIXA_ECONOMICA_FEDERAL",
    "C6_BANK",
    "CLEAR_CORRETORA",
    "EASYINVEST",
    "FOXBIT",
    "GENIAL_INVESTIMENTOS",
    "GUIDE_INVESTIMENTOS",
    "ITAÚ_UNIBANCO",
    "MERCADO_BITCOIN",
    "MODALMAIS",
    "NEON",
    "NEXT",
    "NOVADAX",
    "NUBANK",
    "ORIGINAL",
    "RICO_INVESTIMENTOS",
    "SANTANDER",
    "SAFRA",
    "TORO_INVESTIMENTOS",
    "TERRA_INVESTIMENTOS",
    "XP_INVESTIMENTOS",
  ]),
  tipo: z.enum([
    "ACOES",
    "CDB",
    "CRI",
    "CRA",
    "DEBENTURES",
    "ETF",
    "FIIS",
    "FUNDOS_DE_INVESTIMENTO",
    "LCI",
    "LCA",
    "MOEDA_ESTRANGEIRA",
    "OPCOES",
    "PIB",
    "PREVIDENCIA_PRIVADA",
    "RENDA_FIXA",
    "RENDA_VARIAVEL",
    "TESOURO_DIRETO",
  ]),
  forma_pagamento: z.enum([
    "DINHEIRO",
    "CARTAO_DE_CREDITO",
    "CARTAO_DE_DEBITO",
    "TRANSFERENCIA",
    "PIX",
    "BOLETO",
  ]),
  recorrencia: z.enum([
    "UNICO",
    "DIARIO",
    "SEMANAL",
    "MENSAL",
    "TRIMESTRAL",
    "ANUAL",
  ]),
});

export type SaveExpenseFormSchema = z.infer<typeof schema>;

export function useSaveExpenseForm(defaultValues: SaveExpenseFormSchema) {
  return useForm<SaveExpenseFormSchema>({
    resolver: zodResolver(schema),
    defaultValues,
  });
}

export type UseSaveExpenseForm = ReturnType<typeof useSaveExpenseForm>;
